services:
  ecommerce_frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
    depends_on:
      - ecommerce_backend
    networks:
      - ecommerce_net