services:
  ecommerce_db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce_net

  ecommerce_redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    restart: unless-stopped
    command: redis-server --requirepass "redis_pass"
    ports:
      - "6379:6379"
    networks:
      - ecommerce_net
    # Healthcheck
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_secure_pass_123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  redis-data:
  
networks:
  ecommerce_net:
    driver: bridge
